import "./styles.css";
import projects from "./modules/projects.js";
import createTask from "./modules/createTask.js";
import render from "./modules/render.js";
projects.addProject("school");
createTask("school", "do homework");
const p = projects.getProject();
console.log(p);
render.renderProjects();
render.projectTasks('school');